apiVersion: v1
kind: Service
metadata:
  name: deepstream
  # namespace: deepstream
spec:
  ports:
  - name: rtsp-out
    # nodePort: 31009
    port: 8554
    protocol: TCP
    targetPort: 8554
  selector:
    app: deepstream
  type: NodePort