apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator-kafka-client-delegation
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka.fullname" . }}-kafka-client'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka.fullname" . }}-cluster-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka.fullname" . }}-cluster-operator-global'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka.fullname" . }}-cluster-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator-kafka-broker-delegation
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka.fullname" . }}-kafka-broker'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka.fullname" . }}-cluster-operator'
  namespace: '{{ .Release.Namespace }}'