apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka.fullname" . }}-cluster-operator-namespaced'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka.fullname" . }}-cluster-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator-watched
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka.fullname" . }}-cluster-operator-watched'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka.fullname" . }}-cluster-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator-leader-election
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka.fullname" . }}-cluster-operator-leader-election'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka.fullname" . }}-cluster-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator-entity-operator-delegation
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kafka.fullname" . }}-entity-operator'
subjects:
- kind: ServiceAccount
  name: '{{ include "kafka.fullname" . }}-cluster-operator'
  namespace: '{{ .Release.Namespace }}'