apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka.fullname" . }}-cluster-operator
  labels:
    app: strimzi
  {{- include "kafka.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.clusterOperator.serviceAccount.annotations | nindent 4 }}