config:
  consumedKafka:
    ip: 172.16.44.101
    port: 32438
    topic: my-topic
  producedKafka:
    ip: 172.16.44.101
    port: 32438
    topic: record
  action:
    deltaSeconds: 3
    startMessage: delik
kubernetesClusterDomain: cluster.local
recordingAgent:
  recordingAgent:
    image:
      repository: robolaunchio/recording-agent
      tag: 0.1.1
    imagePullPolicy: IfNotPresent
  replicas: 1
