deepstream:
  deepstream:
    image:
      repository: nvcr.io/nvidia/deepstream
      tag: 6.4-gc-triton-devel
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        nvidia.com/gpu: "1"
  ports:
  - name: rtsp-out
    port: 8554
    protocol: TCP
    targetPort: 8554
  replicas: 1
  type: NodePort
kubernetesClusterDomain: cluster.local
rtspSourceURL: rtsp://172.16.44.101:32608/ds-test
videoSink:
  width: 1280
  height: 720
  rtsp:
    enabled: true
    port: 8554
recording:
  enabled: true
  duration: 3
  interval: 3
  cache: 10
  kafka:
    ip: "172.16.44.101"
    port: 32438
    topic: record