runtimeClassName: nvidia
deepstream:
  deepstream:
    image:
      # repository: nvcr.io/nvidia/deepstream
      # tag: 7.0-gc-triton-devel
      repository: robolaunchio/deepstream-inference
      tag: 7.0-gc-triton-devel-v0.1.1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        nvidia.com/gpu: "1"
  ports:
  - name: rtsp-out
    port: 8554
    protocol: TCP
    targetPort: 8554
  replicas: 1
  type: NodePort
kubernetesClusterDomain: cluster.local
rtspSourceURL: rtsp://172.16.44.172:8554/mystream
boundingBoxes:
  enabled: true
  borderWidth: 5
  borderColor: "0;0;0.7;1"
  textSize: 15
  textColor: "1;1;1;1;"
  textBackgroundColor: "0.3;0.3;0.3;1"
  font: "Arial"
videoSink:
  width: 1280
  height: 720
  rtsp:
    enabled: true
    port: 8554
  kafka:
    enabled: true
    ip: "172.16.44.101"
    port: 32438
    topic: my-topic
inference:
  model:
    url: https://github.com/robolaunch/deepstream-test5-playground/releases/download/test/best.pt
    filename: best.pt
    # url: https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt
    # filename: yolov7.pt
    framework: "YOLOV8" # or YOLOV8
    format: "pt"